"""
reference_library.py

DB-backed, per-user library of firm "reference project" documents (case
studies / past-experience writeups uploaded directly, not generated by the
app) -- separate from proposal_library.py, which holds full proposal packs
archived from the Export Pack tab. Organised by project_type (discipline)
the same way proposal_library.py is, so both libraries share the same
filtering pattern in the UI. See modules/db.py's ReferenceLibraryEntry
model for the schema.

Same shape/conventions as proposal_library.py on purpose -- every function
takes a user_id first, "path" in returned dicts is an opaque entry id (pass
it to read_entry_bytes() to fetch the bytes back), never a filesystem path.
"""

from __future__ import annotations

from modules import db


def upload_reference(
    user_id: str,
    file_bytes: bytes,
    project_type: str,
    filename: str,
    title: str = "",
    tags: str = "",
) -> dict:
    """Stores file_bytes as a new reference library entry owned by user_id.
    Returns a dict in the same shape list_library() entries use, plus
    "path" (an opaque id -- pass it to read_entry_bytes() to fetch the
    bytes back)."""
    folder_name = (project_type or "").strip() or "Unspecified"
    entry = db.ReferenceLibraryEntry(
        user_id=user_id,
        title=(title or "").strip(),
        project_type=folder_name,
        tags=tags or "",
        filename=filename,
        file_bytes=file_bytes,
    )
    with db.get_session() as s:
        s.add(entry)
        s.commit()
        s.refresh(entry)
        return _entry_to_dict(entry)


def list_library(user_id: str, project_type: str | None = None, tag: str | None = None) -> list[dict]:
    """[{title, project_type, tags, uploaded_at, filename, path}] for this
    user's uploaded reference entries, newest first. Optionally filtered by
    project type and/or a single tag (substring match against the
    comma-separated tags field)."""
    with db.get_session() as s:
        q = s.query(db.ReferenceLibraryEntry).filter(db.ReferenceLibraryEntry.user_id == user_id)
        if project_type:
            q = q.filter(db.ReferenceLibraryEntry.project_type == project_type)
        if tag:
            q = q.filter(db.ReferenceLibraryEntry.tags.contains(tag))
        q = q.order_by(db.ReferenceLibraryEntry.uploaded_at.desc())
        return [_entry_to_dict(e) for e in q.all()]


def read_entry_bytes(user_id: str, entry_id: str) -> bytes:
    """Reads back an uploaded reference file's bytes -- scoped to user_id so
    one user can never fetch another user's reference entry by guessing an
    id."""
    with db.get_session() as s:
        entry = s.query(db.ReferenceLibraryEntry).filter(
            db.ReferenceLibraryEntry.id == entry_id, db.ReferenceLibraryEntry.user_id == user_id,
        ).first()
        if not entry:
            raise FileNotFoundError("Reference library entry no longer exists.")
        return entry.file_bytes


def delete_entry(user_id: str, entry_id: str) -> None:
    with db.get_session() as s:
        entry = s.query(db.ReferenceLibraryEntry).filter(
            db.ReferenceLibraryEntry.id == entry_id, db.ReferenceLibraryEntry.user_id == user_id,
        ).first()
        if entry:
            s.delete(entry)
            s.commit()


def _entry_to_dict(entry: db.ReferenceLibraryEntry) -> dict:
    return {
        "title": entry.title,
        "project_type": entry.project_type,
        "tags": entry.tags,
        "uploaded_at": entry.uploaded_at.strftime("%Y%m%d_%H%M%S") if entry.uploaded_at else "",
        "filename": entry.filename,
        "path": entry.id,  # opaque id, same convention as proposal_library.py
    }
